### PR TITLE
Fix imports

### PR DESCRIPTION
**Pull request by wilzbach**
Required for https://github.com/dlang/dmd/pull/7241

It would be great if you could tag a new release afterwards, s.t. the Project Tester
can catch up.

### CODE REVIEW

**Comment by CyberShadow** [comment]
Err, the import is clearly missing, but how do I reproduce this compiler error? The file builds fine with all D versions I tried.

**Comment by CyberShadow** [comment]
Oh sorry, I missed the first line in the PR description.

**Comment by CyberShadow** [comment]
@wilzbach Wait, this still isn't right. I get the error with `-de`, but I don't see it at all with `-dw` even with `-w`. What's going on? I think the DMD pull request needs work.

**Comment by JinShil** [comment]
Are you building with dub?  Could it be that dub is masking the deprecation warning?

**Comment by JinShil** [comment]
I'd like to fix this issue.  Would you be willing to provide me a procedure I can follow to reproduce it?

**Comment by CyberShadow** [comment]
Sure. With DMD 2.081.1:
```shell
$ git clone https://github.com/CyberShadow/ae
$ dmd -o- -dw ae/sys/d/manager.d # no error
$ dmd -o- -de ae/sys/d/manager.d # errors!
```

**Comment by JinShil** [comment]
Reduce test case and issue at https://issues.dlang.org/show_bug.cgi?id=19107

**Comment by CyberShadow** [comment]
Thanks!

**Comment by CyberShadow** [comment]
I'll merge this now as the Bugzilla issue can now be used to track this problem.

**Comment by wilzbach** [comment]
Thanks!
Could you also please tag a new release?

**Comment by CyberShadow** [comment]
I can, but why?

**Comment by JinShil** [comment]
> I can, but why?

So this will pass: https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fdmd/detail/PR-8443/4/pipeline

**Comment by CyberShadow** [comment]
There needs to be at least one release for which all cases show a deprecation message, which means that https://github.com/dlang/dmd/pull/8443 can only be released no earlier than as part of 2.083. Right?

**Comment by JinShil** [comment]
[My sources](https://issues.dlang.org/show_bug.cgi?id=19014#c9) tell me that it's been deprecated for more than 2 years, but I'm not sure I understand.  Which deprecation message is not being displayed?  [https://issues.dlang.org/show_bug.cgi?id=19107](Issue 19107] was only logged, not fixed.

**Comment by CyberShadow** [comment]
> Which deprecation message is not being displayed?

The one described by issue 19107.

> Issue 19107 was only logged, not fixed.

Right, so 19107 will need to be fixed, then a major release to occur including the fix, and only then can PR 8443 be merged.

Unless, of course, we decide that this case is not worth delaying 8443, and the benefit of releasing 8443 earlier outweighs the risk of silently breaking other code as in the case of issue 19107. But I understand the current consensus is that this is not desirable.

**Comment by JinShil** [comment]
https://github.com/dlang/dmd/pull/8519 has been merged, is it now possible to tag a release?

**Comment by thewilsonator** [comment]
Latest release tagged 3rd Oct.

**Pull request merged**
