### PR TITLE
add -L--export-dynamic to standard DFLAGS

### PR DESCRIPTION
**Pull request by MartinNowak**
- same as in dmd releases
- creates a dynamic symbol table for the executable

### CODE REVIEW

**Comment by MartinNowak** [comment]
I'm not a huge fan of this flag as it might change program semantics.
[Issue 11870 – replace dynamic symbol table (--export-dynamic) for backtraces](https://issues.dlang.org/show_bug.cgi?id=11870)
Still I just ran into this while trying to reduce a regression in Higgs.

**Comment by CyberShadow** [comment]
I don't fully understand why this is needed, but I trust you on this.

**Comment by MartinNowak** [comment]
Higgs uses dlsym on it's own executable to load some symbols (in a unittest).
This works for a released dmd, because we ship with this flag, but it fails when using Digger.

**Comment by CyberShadow** [comment]
I see, thanks. But why is this only needed on OSX?

**Comment by MartinNowak** [comment]
> But why is this only needed on OSX?

It's excluded from OSX because this option isn't available there.

**Comment by CyberShadow** [comment]
Ah, misread the patch. Thanks

**Comment by MartinNowak** [comment]
> Thanks

Well, thank you.
This https://bitbucket.org/cybershadow/d.git and Digger is really amazing.
Is the d repo updated automatically?

**Comment by CyberShadow** [comment]
> Is the d repo updated automatically?

Yes, here's the program which generates it: https://github.com/CyberShadow/D-dot-git

> Also looks like you're using the auto-tester results in some way.

Currently I read the autotester status from GitHub, as it's very difficult to contribute to the autotester. Because the API is rate-limited, I have to use an intermediary daemon running on my server: https://github.com/CyberShadow/GHDaemon

**Pull request merged**
